/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_sctimer.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for SCT0 */
/* Definition of peripheral ID */
#define SCTIMER_1_PERIPHERAL SCT0
/* Definition of clock source frequency */
#define SCTIMER_1_CLOCK_FREQ CLOCK_GetFreq(kCLOCK_BusClk)
/* SCTimer_1 interrupt vector ID (number). */
#define SCTIMER_1_IRQN SCT0_IRQn
/* SCTimer_1 interrupt handler identifier. */
#define SCTIMER_1_IRQHANDLER SCT0_IRQHandler
/* SCTimer output 0 mask */
#define SCTIMER_OUTPUT_0_MASK (1U << kSCTIMER_Out_0)
/* SCTimer output 1 mask */
#define SCTIMER_OUTPUT_1_MASK (1U << kSCTIMER_Out_1)
/* SCTimer output 2 mask */
#define SCTIMER_OUTPUT_2_MASK (1U << kSCTIMER_Out_2)
/* SCTimer output 3 mask */
#define SCTIMER_OUTPUT_3_MASK (1U << kSCTIMER_Out_3)
/* SCTimer output 4 mask */
#define SCTIMER_OUTPUT_4_MASK (1U << kSCTIMER_Out_4)
/* SCTimer output 5 mask */
#define SCTIMER_OUTPUT_5_MASK (1U << kSCTIMER_Out_5)
/* SCTimer output 6 mask */
#define SCTIMER_OUTPUT_6_MASK (1U << kSCTIMER_Out_6)
/* SCTimer output 7 mask */
#define SCTIMER_OUTPUT_7_MASK (1U << kSCTIMER_Out_7)

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const sctimer_config_t SCTimer_1_initConfig;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/
void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
